services:
  tmsweb:
    image: registry.danielsplaygrounds.com/docker/images/tms_web:latest
    restart: unless-stopped
    container_name: tmsweb
    volumes:
      - /logs/:/var/log/nginx
    ports:
      - 8185:80
    environment:
      - API_URL=https://api.url.com/api
      - APP_STR= AppTitle
    tty: true
